# Generated by Django 4.2.1 on 2023-06-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='prodect',
            new_name='product',
        ),
    ]
