# Generated by Django 4.2.1 on 2023-06-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_prodect_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='CartItem'),
        ),
    ]
