# Generated by Django 4.2.1 on 2023-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='cart_item'),
        ),
    ]
